import Head from 'next/head';
import UniswapForum from '@/components/DiscourseForum';
import { useProtocolStore } from '@/store/useProtocolStore';
import Header from '@/components/Header';
import LeftSidebar from '@/components/LeftSidebar';
import RightSidebar from '@/components/RightSidebar';
import CategoryTopics from "@/components/CategoryTopics"
import CheckProtocol from '@/components/CheckProtocol';

export default function Home() {
  const { protocol, setProtocol } = useProtocolStore();

  const handleClick = () => {
    console.log('Aave Clicked');
    setProtocol('aave');
    console.log('done');
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Header />
        <CheckProtocol />
        <div className="container mx-auto mt-[30px] flex space-x-[30px]">
          <LeftSidebar />
          {/* <button onClick={() => setProtocol('aave')}>Aave</button>
          <button onClick={() => setProtocol('uniswap')}>Uniswap</button>
          <button onClick={() => setProtocol('compound')}>Compound</button>
          <button onClick={() => setProtocol('optimism')}>Optimism</button>
          <a href={protocol.link} target="_blank" rel="noopener noreferrer">
            {protocol.name} {protocol.link}
          </a> */}
          {/* <UniswapForum /> */}
          <CategoryTopics />
          <RightSidebar />

        </div>
      </main>
    </>
  );
}
