import Head from 'next/head';
import UniswapForum from '@/components/DiscourseForum';
import { useProtocolStore } from '@/store/useProtocolStore';
import Header from '@/components/Header';
import LeftSidebar from '@/components/LeftSidebar';
import RightSidebar from '@/components/RightSidebar';
import CategoryTopics from '@/components/CategoryTopics';

import { storeSlugAndId } from '@/store/useCategoryStore';
import { useEffect } from 'react';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/lib/useAuth';

export default function Home() {
  const { user } = useAuth();
  const { slug } = storeSlugAndId();

  async function getProtocols() {
    if (!user) return;
  
    const { data, error } = await supabase
      .from('user_protocols')
      .select('*')
      .eq('user_id', user.id);
  
    if (error) {
      console.error(error);
      return;
    }
  
    console.log('protocols', data);
  }
  
  getProtocols();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Header />
        <div className="container mx-auto mt-[30px] flex space-x-[30px]">
          <LeftSidebar />
          {!slug ? <UniswapForum /> : <CategoryTopics />}
          <RightSidebar />
        </div>
      </main>
    </>
  );
}
