import Head from 'next/head';
import UniswapForum from '@/components/UniswapForum';
import { useProtocolStore } from '@/store/useProtocolStore';

export default function Home() {
  const { protocol, setProtocol } = useProtocolStore();

  const handleClick = () => {
    console.log('Aave Clicked');

    setProtocol('aave');
    console.log('done');
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <button onClick={() => setProtocol('aave')}>Aave</button>
          <button onClick={() => setProtocol('uniswap')}>Uniswap</button>
          <a href={protocol.link} target="_blank" rel="noopener noreferrer">
            {protocol.name} {protocol.link}
          </a>
          <UniswapForum />
        </div>
      </main>
    </>
  );
}
